### ISSUE TITLE
Still does not seem to be working with PHPStorm 2016.1

### ISSUE THREAD

**Issue by plebeian-org** [textmate/coldfusion.tmbundle#5]
Using this bundle:
https://github.com/textmate/coldfusion.tmbundle

following (seemingly outdated) instructions here:
https://www.jetbrains.com/help/phpstorm/10.0/importing-textmate-bundles.html
and 2016.1 instructions here:
https://www.jetbrains.com/help/phpstorm/2016.1/textmate-bundles.html?origin=old_help

Does not seem to properly syntax highlight, nor code completion. This bundle works fine in Textmate. Really hoping this "glitch" is worked out given my development in the next few months!  :)

<img width="573" alt="screen shot 2016-06-18 at 4 23 48 pm" src="https://cloud.githubusercontent.com/assets/18292613/16174317/b8666d44-3571-11e6-9d17-60e51de4c93b.png">
<img width="517" alt="screen shot 2016-06-18 at 4 24 03 pm" src="https://cloud.githubusercontent.com/assets/18292613/16174319/b866b290-3571-11e6-93a2-7216f84a257a.png">
<img width="839" alt="screen shot 2016-06-18 at 4 27 00 pm" src="https://cloud.githubusercontent.com/assets/18292613/16174318/b8668716-3571-11e6-9f2c-20e162194581.png">

**Comment by davemerrill** [comment]
Sorry not to be super helpful, but you know that IDEA Ultimate has actual built-in support for ColdFusion, yes? If you're doing much CFML, that's really the way to go, not this back door. I don't know specifically what about it is failing, or even how to debug it, but I do know that CFML support in Ultimate is pretty good. Not perfect, but way good enough to be productive, and to say whole-heartedly that I love IDEA, hands-down the best IDE I've ever used. It's what I've been using for full-time professional CFML development for years (and JS, CSS, HTML, SQL, and bit of other stuff). Upgrade, you won't regret it.

That said, I don't mean to interfere with your investigation of this workaround, so carry on :)

**Comment by plebeian-org** [comment]
Hi Dave,

Yes, thanks for the info and your help! We're actually abandoning CF at the
end of this year, and most of what we do it PHP and front-end (at least I
do). IDEA would be the overkill IDE for us in general. I was hoping that
the CF IDEA plug-in would be available to PHPStorm, but alas, no!  :)  and
yes, I agree, the JetBrains IDE is far better than any IDE I've used.
Looking forward to it being my be-all product here on out.

So I've been trying to get the textmate bundle to at least help with syntax
highlighting. Code completion would be nice, and these work fine both in
Coda2 and Textmate. We've recently switched to PHPSTorm so I'm trying to
put in a stop-gap measure for the next year. I'm so close!

I actually found that if I add the .cfm, .cfc and .cfml file types to the
HTML file types area, I get some decent highlighting (all CF variables and
SQL statements are white), but at least the tags render properly, despite
PHPSstorm showing errors on the syntax. If I can't get anything else
working, I'll just stick with this for now.

Zachary

**Comment by infininight** [comment]
I'm not familiar with Jetbrains support for TextMate grammars at all, to be able to properly troubleshoot this it will need to be done by someone familiar with both Jetbrains and that support.

I did look at the doctype rule that produces the first error though and there really isn't anything odd about it, no 2.0 specific features, etc. The only thing that might bring pause is a look-ahead but it's a simple one that shouldn't trip anything up no matter what the regular expression engine is.

Going to close this issue since it is not TextMate specific but I would accept a pull request to fix the issue. Feel free to keep discussing it here regardless.
